Trying to fix autocompile

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -22,16 +22,32 @@ jobs:
         root_file: report/master.tex
         work_in_root_file_dir: true
 
-    - name: Upload PDF
-      uses: actions/upload-artifact@v1
-      with:
-        name: master.pdf
-        path: report/master.pdf
+    - name: Check if PDF exists
+      run: |
+        if [ ! -f report/master.pdf ]; then
+          echo "ERROR: PDF file not found"
+          exit 1
+        fi
 
-    - name: Save logs
-      uses: actions/upload-artifact@v1
-      if: failure()
-      with:
-        name: logs
-        path: .
+    - name: Add, commit, and push PDF
+      run: |
+        git config --global user.email "action@github.com"
+        git config --global user.name "Github Actions"
+        git add report/master.pdf
+        git commit -m "Add report/master.pdf"
+        git push origin HEAD
 
+
+        #    - name: Upload PDF
+        #      uses: actions/upload-artifact@v1
+        #      with:
+        #        name: master.pdf
+        #        path: report/master.pdf
+        #
+        #    - name: Save logs
+        #      uses: actions/upload-artifact@v1
+        #      if: failure()
+        #      with:
+        #        name: logs
+        #        path: .
+        #
